// BILLS LIST 
export const GET_BILLS_LIST_SUCCESS = "GET_BILLS_LIST_SUCCESS";
export const GET_BILLS_LIST_FAIL = "GET_BILLS_LIST_FAIL";

// BILLS DETAIL 
export const GET_BILL_DETAIL_SUCCESS = "GET_BILL_DETAIL_SUCCESS";
export const GET_BILL_DETAIL_FAIL = "GET_BILL_DETAIL_FAIL";

// CREATE BILLS  
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAIL = "CREATE_BILL_FAIL";



    
    
    