// APPOINTMENTS LIST 
export const GET_APPOINTMENTS_LIST_SUCCESS = "GET_APPOINTMENTS_LIST_SUCCESS";
export const GET_APPOINTMENTS_LIST_FAIL = "GET_APPOINTMENTS_LIST_FAIL";

// APPOINTMENTS DETAIL 
export const GET_APPOINTMENT_DETAIL_SUCCESS = "GET_APPOINTMENT_DETAIL_SUCCESS";
export const GET_APPOINTMENT_DETAIL_FAIL = "GET_APPOINTMENT_DETAIL_FAIL";

// CREATE APPOINTMENTS  
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";



    
    
    