# Generated by Django 3.1.5 on 2021-01-09 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0002_auto_20210110_0146'),
        ('bill', '0002_auto_20210109_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
        ),
    ]
