# Generated by Django 3.1.5 on 2021-01-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childteethchart',
            name='patient',
        ),
        migrations.DeleteModel(
            name='AdultTeethChart',
        ),
        migrations.DeleteModel(
            name='ChildTeethChart',
        ),
    ]
