// PATIENTS LIST 
export const GET_PATIENTS_LIST_SUCCESS = "GET_PATIENTS_LIST_SUCCESS";
export const GET_PATIENTS_LIST_FAIL = "GET_PATIENTS_LIST_FAIL";

// PATIENTS DETAIL 
export const GET_PATIENT_DETAIL_SUCCESS = "GET_PATIENT_DETAIL_SUCCESS";
export const GET_PATIENT_DETAIL_FAIL = "GET_PATIENT_DETAIL_FAIL";

// CREATE PATIENTS  
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const CREATE_PATIENT_FAIL = "CREATE_PATIENT_FAIL";



    
    
    