# Generated by Django 3.1.2 on 2020-11-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_adultteethchart_childteethchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultteethchart',
            name='Treatment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.treatment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childteethchart',
            name='Treatment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.treatment'),
            preserve_default=False,
        ),
    ]
