# Generated by Django 3.1.2 on 2020-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201120_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_17',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_18',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_19',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_20',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_21',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_22',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_23',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LL_24',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_25',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_26',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_27',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_28',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_29',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_30',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_31',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='LR_32',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_10',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_11',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_12',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_13',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_14',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_15',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_16',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UL_9',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_1',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_2',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_3',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_4',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_5',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_6',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_7',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultteethchart',
            name='UR_8',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LL_K',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LL_L',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LL_M',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LL_N',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LL_O',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_P',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_Q',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_R',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_S',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_T',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UL_F',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UL_G',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UL_H',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UL_I',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UL_J',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UR_A',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UR_B',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UR_C',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UR_D',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='UR_E',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled Teeth', 'Filled Teeth')], default='None', max_length=50, null=True),
        ),
    ]
