# Generated by Django 3.1.2 on 2020-11-20 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_auto_20201120_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
