# Generated by Django 3.1.2 on 2020-11-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20201120_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='childteethchart',
            name='Treatment',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AdultTeethChart',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='ChildTeethChart',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
