# Generated by Django 3.1.2 on 2020-11-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='adultTeethChart',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='ahildTeethChart',
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_T',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
            preserve_default=False,
        ),
    ]
