# Generated by Django 3.1.2 on 2020-11-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20201130_0008'),
        ('treatment', '0002_auto_20201130_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childteethchart',
            name='LR_T',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Decayed', 'Decayed'), ('Missing', 'Missing'), ('Filled', 'Filled')], default='None', max_length=50, null=True),
        ),
    ]
