# Generated by Django 3.1.2 on 2020-11-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20201130_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='dental_position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='treatment.adultteethchart'),
            preserve_default=False,
        ),
    ]
