# Generated by Django 3.1.2 on 2020-11-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20201130_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='dental_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
