# Generated by Django 3.1.2 on 2020-12-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20201130_0008'),
        ('treatment', '0005_auto_20201130_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultteethchart',
            name='patient',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childteethchart',
            name='patient',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
    ]
