# Generated by Django 3.1.2 on 2020-12-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_auto_20201201_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='dental_position',
            new_name='toothPosition',
        ),
    ]
