# Generated by Django 3.1.5 on 2021-01-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210114_2224'),
        ('payment', '0002_auto_20210114_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
