# Generated by Django 3.1.5 on 2021-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
