# Generated by Django 3.1.5 on 2021-01-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210117_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='treatment',
            new_name='appointment',
        ),
    ]
