# Generated by Django 3.1.5 on 2021-01-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210117_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='doctor',
        ),
    ]
