# Generated by Django 3.1.5 on 2021-01-16 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_remove_bill_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='doctor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
